### PR TITLE
chore: refactor function application over `source_config` values

### PR DESCRIPTION
**Pull request by sloanelybutsurely**
#### Summary of changes

Defines `map_source_config/2`, a function for applying a function to SourceConfig values (both single and top/bottom--tuple).             
                                                                                     
Uses the new `map_source_config/2` function to calculate `alert_status`, `first_scheduled_departures`, and `service_end_statuses_per_source`.

#### Reviewer Checklist
- [x] Any new or changed functions have typespecs
- [x] Tests were added for any new functionality (don't just rely on Codecov)
- [ ] This branch was deployed to the staging environment and is currently running with no unexpected increase in warnings, and no errors or crashes (compare on Splunk: [staging](https://mbta.splunkcloud.com/en-US/app/search/search?q=search%20index%3Drealtime-signs-dev%20%22%5Berror%5D%22%20OR%20%22%5Bwarn%5D%22%20OR%20%22CRASH%22&display.page.search.mode=verbose&dispatch.sample_ratio=1&earliest=-4h%40m&latest=now&sid=1545840107.3874236) vs. [prod](https://mbta.splunkcloud.com/en-US/app/search/search?q=search%20index%3Drealtime-signs-prod%20%22%5Berror%5D%22%20OR%20%22%5Bwarn%5D%22%20OR%20%22CRASH%22&display.page.search.mode=verbose&dispatch.sample_ratio=1&earliest=-4h%40m&latest=now&sid=1545840137.3874305))

### CODE REVIEW

**Comment by digitalcora** [comment]
Since these are both only used in one module, and `simplify` in particular only has a single use, extracting them into public functions on `SourceConfig` feels a bit premature — unless this intentionally doesn't refactor all the places this could be used? (you mentioned "throughout the application")

The improvement in readability for the calling code is nice, though. Maybe these could be private functions?

**Comment by sloanelybutsurely** [comment]
@digitalcora lol hey cora! yeah this is just something i pushed up as an example (referenced here https://github.com/mbta/realtime_signs/pull/797#discussion_r1686713865)

**Comment by sloanelybutsurely** [comment]
@digitalcora I've incorporated your feedback to make this a more reasonable refactoring change. I've changed this to only define `map_source_config/2` as a private function in `Signs.Realtime`.

**Review by digitalcora — APPROVED** [review]
✨

**Pull request merged**
